### ISSUE TITLE
Make a homepage

### ISSUE THREAD

**Issue by Emby01** [Emby01/ErroneousJournalist#13]
You should make a homepage (in the index.html file) that shows all the (recent?) articles and other cool stuff from the website

**Comment by supsa-ak** [comment]
Hi, can I work on this issue. I am participating in Hacktoberfest.

**Comment by Emby01** [comment]
> Hi, can I work on this issue. I am participating in Hacktoberfest.
No thanks, I'm good. You should work on a different repository, this is just me and my friend(s) testing our github skills

**Comment by supsa-ak** [comment]
Okay fine
